version: '3.8'

volumes:
  db_storage:
  n8n_storage:
  qdrant_storage:
  ollama_models:

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - n8n-ollama-shared

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    ports:
      - 5678:5678
    networks:
      - n8n-ollama-shared
    links:
      - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    volumes:
      - qdrant_storage:/qdrant/storage
    ports:
      - 6333:6333
    networks:
      - n8n-ollama-shared

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: "no"
    ports:
      - 11434:11434
    networks:
      - n8n-ollama-shared
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_HOST=0.0.0.0:11434
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
    labels:
      desktop.docker.io/wsl-distro: Ubuntu-24.04
      org.opencontainers.image.ref.name: ubuntu
      org.opencontainers.image.version: 20.04
    runtime: runc

networks:
  n8n-ollama-shared:
    external: true

